[book]
title = "Template for Rust project"
authors = "Valentin Colin"

[output.html]
git-repository-url = "https://github.com/ValentinColin/rust-template-project"
site-url = "https://ValentinColin.github.io/rust-template-project/"
