[book]
title = "Template for Rust project"
authors = ["Valentin Colin"]
language = "en"
multilingual = false

[output.html]
git-repository-url = "https://github.com/ValentinColin/rust-template-project"
mathjax-support = false

[output.html.playground]
editable = false
