name: github pages

on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'
  workflow_dispatch:

defaults:
  run:
    working-directory: docs

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - name: Read .env
        id: mdbook-version
        run: |
          source .env
          echo "::set-output name=MDBOOK_VERSION::${MDBOOK_VERSION}"
      - name: Setup mdbook
        uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: '${{ steps.mdbook-version.outputs.MDBOOK_VERSION }}'

      - name: Build
        run: |
          pwd
          mdbook build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: book
